spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgresql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml